"""add exp to user table

Revision ID: 32d2c95e2f06
Revises: 66ab6e070a46
Create Date: 2025-01-30 07:25:25.817540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d2c95e2f06'
down_revision: Union[str, None] = '66ab6e070a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('exp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'exp')
    # ### end Alembic commands ###
