"""Fix relation between book and gener

Revision ID: 66ab6e070a46
Revises: 46c2c78cedc3
Create Date: 2025-01-30 05:53:37.575119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ab6e070a46'
down_revision: Union[str, None] = '46c2c78cedc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('gener', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'book', 'gener', ['gener'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'gener')
    # ### end Alembic commands ###
