"""Fix relation Author Book

Revision ID: 6bc34f442c28
Revises: 988f9d85faf4
Create Date: 2025-01-29 17:03:17.657029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc34f442c28'
down_revision: Union[str, None] = '988f9d85faf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'unit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('book_author', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_author', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('book', 'unit',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
