"""create customer model

Revision ID: fc16f0484829
Revises: 7559cc1bb4d2
Create Date: 2025-01-29 01:22:50.065462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc16f0484829'
down_revision: Union[str, None] = '7559cc1bb4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('subscription_model', sa.Enum('FREE', 'PLUS', 'PREMIUM', name='subscriptionmodel'), nullable=False),
    sa.Column('subscription_end', sa.DateTime(), nullable=True),
    sa.Column('wallet_money', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
